version: '3.1'

services:
  db:
    container_name: mysql-8.0.28
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3308:3306"

  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - "9080:8080"

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "9081:80"
      - "9025:25"
